unit inLibFacturas;

interface

type
  TLineaFactura = class
private
  NRO_FACTURA_LINEA,
  SERIE_FACTURA_LINEA,
  LINEA_FACTURA_LINEA,
  CODIGO_ARTICULO_FACTURA_LINEA,
  CODIGO_FAMILIA_FACTURA_LINEA,
  NOMBRE_FAMILIA_FACTURA_LINEA,
  FECHA_ENTREGA_FACTURA_LINEA,
  TIPO_CANTIDAD_ARTICULO_FACTURA_LINEA,
  ESIMP_INCL_TARIFA_FACTURA_LINEA,
  TIPOIVA_ARTICULO_FACTURA_LINEA,
  DESCRIPCION_ARTICULO_FACTURA_LINEA,
  CODIGO_TARIFA_FACTURA_LINEA,
  CANTIDAD_FACTURA_LINEA,
  PRECIOSALIDA_FACTURA_LINEA,
  PORCEN_DTO_FACTURA_LINEA,
  PRECIO_DTO_FACTURA_LINEA,
  PRECIOVENTA_SIVA_ARTICULO_FACTURA_LINEA,
  PORCEN_IVA_FACTURA_LINEA,
  PRECIOVENTA_CIVA_ARTICULO_FACTURA_LINEA,
  TOTAL_FACTURA_LINEA : String;

end;

implementation

end.
